#!/bin/sh

#
# jupyter tool
#
/usr/bin/invoke_app "$@" -t 2dcnt \
                         -C "start_jupyter -T @tool -t CNT_Forest_Growth.ipynb" \
                         -u anaconda-6 \
                         -r none \
                         -w headless
